### ISSUE TITLE
搜索内容不可用

### ISSUE THREAD

**Issue by Boom199801** [saifeiLee/xhs-js#2]
<img width="910" alt="image" src="https://github.com/user-attachments/assets/3d446dd7-a9cb-499a-b7ef-1e1855c147e1">

大佬，搜索内容不可用，但是搜索用户可以

**Comment by saifeiLee** [comment]
已处理，可以测试一下。
https://github.com/saifeiLee/xhs-js/commit/f4b7ecf55818491730234fb94ca89bf36554f281

**Comment by Boom199801** [comment]
好滴，谢谢，我测试一下
