### ISSUE TITLE
添加额外api

### ISSUE THREAD

**Issue by I-BlueDragon** [saifeiLee/xhs-js#3]
有考虑添加获取用户所有笔记的api吗？

**Comment by saifeiLee** [comment]
> 有考虑添加获取用户所有笔记的api吗？

🌟star太少了，没动力做。

**Comment by I-BlueDragon** [comment]
> > 有考虑添加获取用户所有笔记的api吗？
> 
> 🌟star太少了，没动力做。

已star，希望能添加一下，这样会有更多人star

**Comment by saifeiLee** [comment]
> > > 有考虑添加获取用户所有笔记的api吗？
> > 
> > 
> > 🌟star太少了，没动力做。
> 
> 已star，希望能添加一下，这样会有更多人star

已支持。

**Comment by I-BlueDragon** [comment]
> > > > 有考虑添加获取用户所有笔记的api吗？
> > > 
> > > 
> > > 🌟star太少了，没动力做。
> > 
> > 
> > 已star，希望能添加一下，这样会有更多人star
> 
> 已支持。

很强！
